# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pocsite.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer_mail', models.EmailField(max_length=254)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField(default=pocsite.models.one_month_from_now)),
                ('status', models.CharField(blank=True, choices=[('n', 'Not started'), ('v', 'Valid'), ('e', 'Expired'), ('o', 'Void'), ('c', 'Claimed')], default='v', help_text='Contract status', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.TextField(help_text='a simple description of the product')),
                ('is_published', models.BooleanField(default=True, help_text='allow this product to be subscribed')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='price of the product', max_digits=6)),
                ('base_payout', models.DecimalField(decimal_places=2, help_text='the amount to reimburse the customer if insurance is activated', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quote_payout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(blank=True, choices=[('p', 'Pending'), ('e', 'Expired'), ('a', 'Accepted'), ('r', 'Refused')], default='p', help_text='Quote status', max_length=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pocsite.Product')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pocsite.Product'),
        ),
        migrations.AddField(
            model_name='contract',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pocsite.Quote'),
        ),
    ]
